1786: set time zone utc
ITK-Leantime/leantime-dataexport pull request #15
Opened 2024-06-26 06:20 UTC by sinejespersen

#### Link to ticket

https://leantime.itkdev.dk/dashboard/show?tab=ticketdetails#/tickets/showTicket/1786

#### Description

hmm..

When exporting the file, the date from worked in a mysterious way. If i set timezone UTC, it works as expected. 

#### Screenshot of the result

n/a

2024-07-03 07:03 UTC, sinejespersen commented
@rimi-itk If you find it in your heart to approve this, then just feel free to merge it as well :)

2024-07-03 08:45 UTC, rimi-itk requested changes

2024-07-03 08:45 UTC, rimi-itk commented on Services/AbstractExporter.php
> +                $returnDate = CarbonImmutable::createFromFormat('!' . $format, $value) ?: new CarbonImmutable($default);
This line is superfluous and therefore the `if` statement is too.

2024-07-03 08:45 UTC, rimi-itk commented on Services/AbstractExporter.php
> +        return new CarbonImmutable($default);
`$default` should be handled just like `$value`, i.e. passed through the date time helper functions, and then the whole function body can (probably) be rewritten to something like

```php
$value ??= $default;

return null !== $value ? $this->dateTimeHelper->parseUserDateTime($value)->setToDbTimezone() : null;
```

2024-07-04 11:38 UTC, sinejespersen commented on Services/AbstractExporter.php
> +        return new CarbonImmutable($default);
I've tested it, and it works :)

2024-07-04 13:45 UTC, rimi-itk approved these changes

2024-07-04 14:50 UTC, merged